### ISSUE TITLE
Wrong entry point in package.json

### ISSUE THREAD

**Issue by ebuster** [houd1ni/WebsocketPromisify#35]
Hi,

I start using wspromisify in my Quasar project, based on VIte, and get the following error on build:

```
[vite] Internal server error: Failed to resolve entry for package "wspromisify". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "wspromisify". The package may have incorrect main/module/exports specified in its package.json.
Plugin: vite:import-analysis
File: ui/src/api/wsp.ts
at packageEntryFailure (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:40970:11)
at resolvePackageEntry (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:40966:9)
at tryNodeResolve (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:40773:20)
at Context.resolveId (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:40581:28)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.resolveId (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:39254:32)
at async TransformContext.resolve (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:39028:23)
at async normalizeUrl (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:58354:34)
at async TransformContext.transform (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:58509:57)
at async Object.transform (ui/node_modules/vite/dist/node/chunks/dep-689425f3.js:39317:30)
```
And actually it is not correct:
<img width="768" alt="Screenshot 2023-02-25 at 11 27 34" src="https://user-images.githubusercontent.com/3728965/221347417-1c8a1bd0-7e3b-411c-a4c5-1daed2830db3.png">

**Comment by houd1ni** [comment]
Damn, I was thinking, I've changed all my projects to "exports": { import: ..., require: ...} schema.
Could you, please, try that ? This is for unification. If works for you, I'd merge it and rollout a version within a few hours.

```javascript
  "exports": {
    ".": {
      "import": "./dist/bundle.mjs",
      "require": "./dist/bundle.cjs"
    }
  }
```

**Comment by ebuster** [comment]
But current version of Promisify is already contains this "exports", and seems like it ignored by Vite.
Unfortunately I don't know what Vite's options related to this behaviour, but I changed my local package.json like in provided MR and build passed.

**Comment by houd1ni** [comment]
Weird. Gonna test it tomorrow. Will find out why.

**Comment by ebuster** [comment]
Sorry, I don't know how and where modern "exports" expected to work (and what is your test plan), but old one main\module props obviously points to not existing files. If you don't plan to remove them completely, in favour of new ones, they need to be fixed even without any testing.

**Comment by houd1ni** [comment]
Have tested it with vite@4.1.4 and it does not fail if these two fields got removed to not confuse the bundler.
Would you better remove them instead of fixing the paths then to get the PR merged ? :shipit:

**Comment by ebuster** [comment]
Removed.

**Comment by houd1ni** [comment]
@ebuster published with the fix. `npm i -S wspromisify@2.4.4`
